var N = null;var sourcesIndex = {};
sourcesIndex["bonsaidb_counter_client"] = {"name":"","files":["main.rs"]};
sourcesIndex["bonsaidb_counter_server"] = {"name":"","files":["main.rs"]};
sourcesIndex["bonsaidb_counter_shared"] = {"name":"","files":["lib.rs"]};
sourcesIndex["gooey"] = {"name":"","files":["app.rs","browser.rs","headless.rs","kludgine.rs","lib.rs","style.rs"]};
sourcesIndex["gooey_browser"] = {"name":"","files":["lib.rs","utils.rs"]};
sourcesIndex["gooey_core"] = {"name":"","dirs":[{"name":"styles","files":["alignment.rs","colors.rs","font_family.rs","font_size.rs","font_style.rs","lines.rs","mod.rs","style_sheet.rs","surround.rs","weight.rs"]},{"name":"widget","files":["transmogrifier_context.rs"]}],"files":["frontend.rs","gooey.rs","lib.rs","widget.rs"]};
sourcesIndex["gooey_kludgine"] = {"name":"","files":["lib.rs"]};
sourcesIndex["gooey_rasterizer"] = {"name":"","files":["events.rs","lib.rs","state.rs","transmogrifier.rs"]};
sourcesIndex["gooey_renderer"] = {"name":"","files":["lib.rs"]};
sourcesIndex["gooey_text"] = {"name":"","dirs":[{"name":"wrap","files":["measured.rs","tokenizer.rs"]}],"files":["lib.rs","prepared.rs","wrap.rs"]};
sourcesIndex["gooey_widgets"] = {"name":"","dirs":[{"name":"button","files":["browser.rs","rasterizer.rs"]},{"name":"checkbox","files":["browser.rs","rasterizer.rs"]},{"name":"component","files":["browser.rs","rasterizer.rs"]},{"name":"container","files":["browser.rs","rasterizer.rs"]},{"name":"label","files":["browser.rs","rasterizer.rs"]},{"name":"layout","files":["browser.rs","rasterizer.rs"]}],"files":["button.rs","checkbox.rs","component.rs","container.rs","label.rs","layout.rs","lib.rs"]};
sourcesIndex["xtask"] = {"name":"","files":["main.rs"]};
createSourceSidebar();
